spring.application.name=demo
spring.datasource.url=jdbc:postgresql://dpg-ctb38cm8ii6s73fu0bbg-a.oregon-postgres.render.com:5432/curriculospringboot
spring.datasource.username=curriculospringboot_user
spring.datasource.password=qUvVovw1o0jJF9BJ973z70SMulB4Ggth
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true